
language: python # this works for Linux but is an error on macOS or Windows
node_js: stable
addons:
      chrome: stable
#env:
#  global:
    #- CHROME_BIN=/Users/travis/build/chrome #/usr/bin/google-chrome
    #- export DISPLAY=:99.0
    #- sh -e /etc/init.d/xvfb start
jobs:
  include:
  # cant get the windows test to work, no clue how to install chrome and find the binary
  # chrome: stable addon doesnt seem to install chrome for windows?
  #- name: "Python 3.8.0 on Windows"
  #  os: windows           # Windows 10.0.17134 N/A Build 17134
  #  language: shell
  #  before_install:
  #    - choco install python --version 3.8.0
  #    - python -m pip install --upgrade pip
  #
  #  env:
  #     global:
  #      - PATH=/c/Python38:/c/Python38/Scripts:$PATH
  #       -CHROME_BIN=%AppData%\Local\Google\Chrome\Application\chome.exe
  #       - C:\Users\travis\AppData\Local\Google\Chrome\Application\chome.exe
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell
install:
  - pip3 install -r requirements.txt
  - pip3 install .
  #- travis_wait 30 mvn install

script: python3 test.py || python test.py

notifications:
  email:
    recipients:
    - pe.lacour@gmail.com
    on_failure: always
